config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :books, except: [:show] do
    resources :chapters, only: [:index, :create]
  end
  resources :chapters, only: [:edit, :update, :destroy] do
    resources :posts, except: [:new, :show]
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  has_many :chapters, dependent: :destroy

  def next_chapter_number
    self.chapters.count + 1
  end
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :book
  has_many :posts, dependent: :destroy
  validates :number, presence: :true, numericality: { greater_than: 0 }
  validates :title, presence: :true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :chapter
  belongs_to :user
  has_rich_text :content

  validates :content, presence: true
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :admin_authorization, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_book, only: [:edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all.order(:created_at)
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path, notice: 'Book was successfully created.' 
    else
      render :new 
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    if @book.update(book_params)
      redirect_to books_path, notice: 'Book was successfully updated.'
    else
      render :edit 
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title)
    end

    def admin_authorization
      redirect_to books_path unless current_user.admin?
    end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :admin_authorization, only: [:create, :edit, :update, :destroy]

  def index
    @book = Book.find(params[:book_id])
    @chapter = Chapter.new
  end

  def create
    @book = Book.find(params[:book_id])
    @chapter = Chapter.new(chapter_params)
    @chapter.number = @book.next_chapter_number
    @chapter.book_id = params[:book_id]

    if @chapter.save
      redirect_to book_chapters_path(@chapter.book), notice: "Chapter successfully created"
    else
      flash.now[:notice] = "Chapter creation unsuccessful"
      render :index
    end
  end

  def edit
    @chapter = Chapter.find(params[:id])
  end

  def update
    @chapter = Chapter.find(params[:id])
    if @chapter.update(chapter_params)
      redirect_to book_chapters_path(@chapter.book), notice: 'Chapter was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    chapter = Chapter.find(params[:id])
    chapter.destroy
    redirect_to book_chapters_path(chapter.book), notice: 'Chapter was successfully destroyed.'
  end

  private
  def chapter_params
    params.require(:chapter).permit(:title)
  end

  def admin_authorization
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @chapter = Chapter.find(params[:chapter_id])
    @post = Post.new
  end

  def create
    @chapter = Chapter.find(params[:chapter_id])
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.chapter_id = @chapter.id

    if @post.save
      redirect_to chapter_posts_path(@chapter), notice: "Post created successfully"
    else
      flash.now[:notice] = "Post creation unsuccessful"
      render :index
    end
  end

  def edit
    @chapter = Chapter.find(params[:chapter_id])
    @post = Post.find(params[:id])

    if @post.user != current_user
      redirect_to chapter_posts_path(@chapter), notice: "You cannot edit that post"
    end
  end

  def update
    @chapter = Chapter.find(params[:chapter_id])
    @post = Post.find(params[:id])

    if @post.user != current_user
      redirect_to chapter_posts_path(@chapter), notice: "You cannot update that post"
    elsif @post.update(post_params)
      redirect_to chapter_posts_path(@chapter), notice: 'Post was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to chapter_posts_path(@post.chapter), notice: "You cannot delete that post"
    else
      @post.destroy
      redirect_to chapter_posts_path(@post.chapter), notice: "Post was successfully destroyed"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Chapter Index', @book %> |
<%= link_to 'Book Index', books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<% if current_user.admin? %>
  <%= link_to 'New Book', new_book_path %>
<% end %>
<br />
<br />
<table>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to "#{book.title}", book_chapters_path(book), id: "book-title-link" %></td>
        <% if current_user.admin? %>
        <td>
          <%= link_to "Edit", edit_book_path(book), class: "book-edit-link" %>
        </td>
        <td>
          <%= link_to "Delete", book, method: :delete, data: { confirm: "Deleting the book will delete all associated chapters and posts, are you sure you wish to continue?" } %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/chapters/edit.html.erb
<h1>Editing Chapter <%= @chapter.number %> of <%= @chapter.book.title %></h1>

<%= form_with(model: @chapter, local: true) do |form| %>
  <% if @chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
        <% @chapter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', book_chapters_path(@chapter.book) %>

app/views/chapters/index.html.erb
<h2><%= @book.title %></h2>

<h3>Chapters</h3>

<% if @chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
        <% @chapter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= form_with model: [@book, @chapter], local: true do |form| %>
<table>
  <tbody>
  <% if @book.chapters.count > 0 %>
  <% @book.chapters.order(:number).each do |chapter| %>
    <tr>
      <td>
        <%= chapter.number %>
      </td>
      <td>
        <%= link_to "#{chapter.title}", chapter_posts_path(chapter) %>
      </td>
      <% if current_user.admin? %>
      <td>
        <%= link_to 'Edit', edit_chapter_path(chapter), id: "chapter-#{chapter.number}", class: 'chapter-edit-link' %>
      </td>
      <td>
      <% if (chapter.number == @book.chapters.count) %>
        <%= link_to 'Delete', chapter_path(chapter), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      </td>
      <% end %>
    </tr>
  <% end %>
  <% end %>
  <% if current_user.admin? %>
  <tr>
    <td>
      <%= @book.next_chapter_number %>
    </td>
    <td>
      <%= form.text_field :title %>
    </td>
    <td>
      <%= form.submit "Save" %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>
<% end %>

<%= link_to "Books", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookclub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ul class="hmenu">
    <%= render 'devise/menu/login_items' %>
  </ul>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_new_post.html.erb
<%= form_with model: [@chapter, @post], local: true do |form| %>
  <div class="post">
  <h2>New Post:</h2>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Editing Post</h2>

<%= render "new_post" %>

<%= link_to "Back", chapter_posts_path(@chapter) %>

app/views/posts/index.html.erb
<h1><%= @chapter.book.title %></h1>
<h2>Chapter <%= @chapter.number %> Discussion</h2> <%= link_to "Back", book_chapters_path(@chapter.book) %>

<% @chapter.posts.order(:created_at).each do |post| %>
  <div class="post">
      <strong><%= post.title %></strong> Posted at <%= post.created_at %> by <%= post.user.email %> 
      <div class="content"><%= post.content %></div>
      <% if (current_user.posts.include?(post)) %>
      <%= link_to "Edit", edit_chapter_post_path(@chapter, post), class: "edit-post-link" %> | 
      <%= link_to "Delete", chapter_post_path(@chapter, post), method: :delete, class: "delete-post-link", data: { confirm: "Are you sure you would like to delete this post?" } %>
      <% end %>
  </div>
<% end %>

<%= render "new_post" %>